### ISSUE TITLE
TST: enable creating Client / Backend with parametrized data

### ISSUE THREAD

**Issue by shilorigins** [pcdshub/superscore#103]
## Current Behavior

We have specific fixtures for a backend and a client with data from `filestore.json`, but none for e.g. `linac_data` or a second `json` file.
## Expected Behavior

It would be nice to be able to call the `filestore_backend` fixture with a file arg for it to expose, or with data for it to write to a temp file and expose.

**Comment by tangkong** [comment]
I was musing about this at some point, I forget if it was in this context or not.  We could make a helper function that constructs a client given some parameters, rather than having specific fixtures with specific configuration as we do now.  

If we don't make these fixtures, we'll have to make sure we're deliberate with cleaning up and resetting state, since pytest isn't doing it for us.  

But I very much agree that being to run tests on a matrix of backends and data would be nice
